/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bluedevel_zlib_FastInflater */

#ifndef _Included_com_bluedevel_zlib_FastInflater
#define _Included_com_bluedevel_zlib_FastInflater
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bluedevel_zlib_FastInflater
 * Method:    initIDs
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_bluedevel_zlib_FastInflater_initIDs
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_bluedevel_zlib_FastInflater
 * Method:    init
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_com_bluedevel_zlib_FastInflater_init
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_bluedevel_zlib_FastInflater
 * Method:    inflateBytes
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_com_bluedevel_zlib_FastInflater_inflateBytes
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_bluedevel_zlib_FastInflater
 * Method:    reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_bluedevel_zlib_FastInflater_reset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_bluedevel_zlib_FastInflater
 * Method:    end
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_bluedevel_zlib_FastInflater_end
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
