/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_duplexsystem_jzlibng_FastDeflater */

#ifndef _Included_io_github_duplexsystem_jzlibng_FastDeflater
#define _Included_io_github_duplexsystem_jzlibng_FastDeflater
#ifdef __cplusplus
extern "C" {
#endif
#undef io_github_duplexsystem_jzlibng_FastDeflater_DEFLATED
#define io_github_duplexsystem_jzlibng_FastDeflater_DEFLATED 8L
#undef io_github_duplexsystem_jzlibng_FastDeflater_NO_COMPRESSION
#define io_github_duplexsystem_jzlibng_FastDeflater_NO_COMPRESSION 0L
#undef io_github_duplexsystem_jzlibng_FastDeflater_BEST_SPEED
#define io_github_duplexsystem_jzlibng_FastDeflater_BEST_SPEED 1L
#undef io_github_duplexsystem_jzlibng_FastDeflater_BEST_COMPRESSION
#define io_github_duplexsystem_jzlibng_FastDeflater_BEST_COMPRESSION 9L
#undef io_github_duplexsystem_jzlibng_FastDeflater_DEFAULT_COMPRESSION
#define io_github_duplexsystem_jzlibng_FastDeflater_DEFAULT_COMPRESSION -1L
#undef io_github_duplexsystem_jzlibng_FastDeflater_FILTERED
#define io_github_duplexsystem_jzlibng_FastDeflater_FILTERED 1L
#undef io_github_duplexsystem_jzlibng_FastDeflater_HUFFMAN_ONLY
#define io_github_duplexsystem_jzlibng_FastDeflater_HUFFMAN_ONLY 2L
#undef io_github_duplexsystem_jzlibng_FastDeflater_DEFAULT_STRATEGY
#define io_github_duplexsystem_jzlibng_FastDeflater_DEFAULT_STRATEGY 0L
#undef io_github_duplexsystem_jzlibng_FastDeflater_NO_FLUSH
#define io_github_duplexsystem_jzlibng_FastDeflater_NO_FLUSH 0L
#undef io_github_duplexsystem_jzlibng_FastDeflater_SYNC_FLUSH
#define io_github_duplexsystem_jzlibng_FastDeflater_SYNC_FLUSH 2L
#undef io_github_duplexsystem_jzlibng_FastDeflater_FULL_FLUSH
#define io_github_duplexsystem_jzlibng_FastDeflater_FULL_FLUSH 3L
#undef io_github_duplexsystem_jzlibng_FastDeflater_FINISH
#define io_github_duplexsystem_jzlibng_FastDeflater_FINISH 4L
/*
 * Class:     io_github_duplexsystem_jzlibng_FastDeflater
 * Method:    init
 * Signature: (IIZ)J
 */
JNIEXPORT jlong JNICALL Java_io_github_duplexsystem_jzlibng_FastDeflater_init
  (JNIEnv *, jclass, jint, jint, jboolean);

/*
 * Class:     io_github_duplexsystem_jzlibng_FastDeflater
 * Method:    setDictionary
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_io_github_duplexsystem_jzlibng_FastDeflater_setDictionary
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     io_github_duplexsystem_jzlibng_FastDeflater
 * Method:    setDictionaryBuffer
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_io_github_duplexsystem_jzlibng_FastDeflater_setDictionaryBuffer
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     io_github_duplexsystem_jzlibng_FastDeflater
 * Method:    deflateBytesBytes
 * Signature: (J[BII[BIIII)J
 */
JNIEXPORT jlong JNICALL Java_io_github_duplexsystem_jzlibng_FastDeflater_deflateBytesBytes
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     io_github_duplexsystem_jzlibng_FastDeflater
 * Method:    deflateBytesBuffer
 * Signature: (J[BIIJIII)J
 */
JNIEXPORT jlong JNICALL Java_io_github_duplexsystem_jzlibng_FastDeflater_deflateBytesBuffer
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint, jlong, jint, jint, jint);

/*
 * Class:     io_github_duplexsystem_jzlibng_FastDeflater
 * Method:    deflateBufferBytes
 * Signature: (JJI[BIIII)J
 */
JNIEXPORT jlong JNICALL Java_io_github_duplexsystem_jzlibng_FastDeflater_deflateBufferBytes
  (JNIEnv *, jobject, jlong, jlong, jint, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     io_github_duplexsystem_jzlibng_FastDeflater
 * Method:    deflateBufferBuffer
 * Signature: (JJIJIII)J
 */
JNIEXPORT jlong JNICALL Java_io_github_duplexsystem_jzlibng_FastDeflater_deflateBufferBuffer
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jint, jint, jint);

/*
 * Class:     io_github_duplexsystem_jzlibng_FastDeflater
 * Method:    getAdler
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_github_duplexsystem_jzlibng_FastDeflater_getAdler
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_duplexsystem_jzlibng_FastDeflater
 * Method:    reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_duplexsystem_jzlibng_FastDeflater_reset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_duplexsystem_jzlibng_FastDeflater
 * Method:    end
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_duplexsystem_jzlibng_FastDeflater_end
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
