/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_duplexsystem_jzlibng_FastInflater */

#ifndef _Included_io_github_duplexsystem_jzlibng_FastInflater
#define _Included_io_github_duplexsystem_jzlibng_FastInflater
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_duplexsystem_jzlibng_FastInflater
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_duplexsystem_jzlibng_FastInflater_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     io_github_duplexsystem_jzlibng_FastInflater
 * Method:    init
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_io_github_duplexsystem_jzlibng_FastInflater_init
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     io_github_duplexsystem_jzlibng_FastInflater
 * Method:    setDictionary
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_io_github_duplexsystem_jzlibng_FastInflater_setDictionary
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     io_github_duplexsystem_jzlibng_FastInflater
 * Method:    setDictionaryBuffer
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_io_github_duplexsystem_jzlibng_FastInflater_setDictionaryBuffer
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     io_github_duplexsystem_jzlibng_FastInflater
 * Method:    inflateBytesBytes
 * Signature: (J[BII[BII)J
 */
JNIEXPORT jlong JNICALL Java_io_github_duplexsystem_jzlibng_FastInflater_inflateBytesBytes
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     io_github_duplexsystem_jzlibng_FastInflater
 * Method:    inflateBytesBuffer
 * Signature: (J[BIIJI)J
 */
JNIEXPORT jlong JNICALL Java_io_github_duplexsystem_jzlibng_FastInflater_inflateBytesBuffer
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint, jlong, jint);

/*
 * Class:     io_github_duplexsystem_jzlibng_FastInflater
 * Method:    inflateBufferBytes
 * Signature: (JJI[BII)J
 */
JNIEXPORT jlong JNICALL Java_io_github_duplexsystem_jzlibng_FastInflater_inflateBufferBytes
  (JNIEnv *, jobject, jlong, jlong, jint, jbyteArray, jint, jint);

/*
 * Class:     io_github_duplexsystem_jzlibng_FastInflater
 * Method:    inflateBufferBuffer
 * Signature: (JJIJI)J
 */
JNIEXPORT jlong JNICALL Java_io_github_duplexsystem_jzlibng_FastInflater_inflateBufferBuffer
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jint);

/*
 * Class:     io_github_duplexsystem_jzlibng_FastInflater
 * Method:    getAdler
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_github_duplexsystem_jzlibng_FastInflater_getAdler
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_duplexsystem_jzlibng_FastInflater
 * Method:    reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_duplexsystem_jzlibng_FastInflater_reset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_duplexsystem_jzlibng_FastInflater
 * Method:    end
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_duplexsystem_jzlibng_FastInflater_end
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
