/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bluedevel_zlib_FastDeflater */

#ifndef _Included_com_bluedevel_zlib_FastDeflater
#define _Included_com_bluedevel_zlib_FastDeflater
#ifdef __cplusplus
extern "C" {
#endif
#undef com_bluedevel_zlib_FastDeflater_DEFLATED
#define com_bluedevel_zlib_FastDeflater_DEFLATED 8L
#undef com_bluedevel_zlib_FastDeflater_NO_COMPRESSION
#define com_bluedevel_zlib_FastDeflater_NO_COMPRESSION 0L
#undef com_bluedevel_zlib_FastDeflater_BEST_SPEED
#define com_bluedevel_zlib_FastDeflater_BEST_SPEED 1L
#undef com_bluedevel_zlib_FastDeflater_BEST_COMPRESSION
#define com_bluedevel_zlib_FastDeflater_BEST_COMPRESSION 9L
#undef com_bluedevel_zlib_FastDeflater_DEFAULT_COMPRESSION
#define com_bluedevel_zlib_FastDeflater_DEFAULT_COMPRESSION -1L
#undef com_bluedevel_zlib_FastDeflater_FILTERED
#define com_bluedevel_zlib_FastDeflater_FILTERED 1L
#undef com_bluedevel_zlib_FastDeflater_HUFFMAN_ONLY
#define com_bluedevel_zlib_FastDeflater_HUFFMAN_ONLY 2L
#undef com_bluedevel_zlib_FastDeflater_DEFAULT_STRATEGY
#define com_bluedevel_zlib_FastDeflater_DEFAULT_STRATEGY 0L
#undef com_bluedevel_zlib_FastDeflater_NO_FLUSH
#define com_bluedevel_zlib_FastDeflater_NO_FLUSH 0L
#undef com_bluedevel_zlib_FastDeflater_SYNC_FLUSH
#define com_bluedevel_zlib_FastDeflater_SYNC_FLUSH 2L
#undef com_bluedevel_zlib_FastDeflater_FULL_FLUSH
#define com_bluedevel_zlib_FastDeflater_FULL_FLUSH 3L
/*
 * Class:     com_bluedevel_zlib_FastDeflater
 * Method:    initIDs
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_bluedevel_zlib_FastDeflater_initIDs
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_bluedevel_zlib_FastDeflater
 * Method:    init
 * Signature: (IIZ)J
 */
JNIEXPORT jlong JNICALL Java_com_bluedevel_zlib_FastDeflater_init
  (JNIEnv *, jclass, jint, jint, jboolean);

/*
 * Class:     com_bluedevel_zlib_FastDeflater
 * Method:    deflateBytes
 * Signature: (J[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_bluedevel_zlib_FastDeflater_deflateBytes
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint, jint);

/*
 * Class:     com_bluedevel_zlib_FastDeflater
 * Method:    reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_bluedevel_zlib_FastDeflater_reset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_bluedevel_zlib_FastDeflater
 * Method:    end
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_bluedevel_zlib_FastDeflater_end
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
